### ISSUE TITLE
'pgm_read_word_near' was not declared in this scope

### ISSUE THREAD

**Issue by bloatedwarthog** [pkourany/RGBPixelClock_IDE#1]
Veryfing code using this library in Particle Build fails with this error:

```
RGBPixelClock/fix_fft.cpp:178:58: error: 'pgm_read_word_near' was not declared in this scope
            wr =  pgm_read_word_near(Sinewave   j N_WAVE/4)
```

**Comment by pkourany** [comment]
@bloatedwarthog, I'll have a look tonight.  Thanks for posting!

**Comment by bloatedwarthog** [comment]
Thank you sir. I sent you a pull request for a fix. On Electron, I just got rid of the PROGMEM stuff. Not sure that's the right answer for the Proton or other versions of the particle. I only have an Electron.

**Comment by pkourany** [comment]
@bloatedwarthog, I could not replicate your error so not sure the conditions under which you got those.  As such, there is not need for the PR.
